apiVersion: v1
kind: Service
metadata:
  name: {{ template "lookout-html-analyzer.fullname" . }}
  labels:
    app: {{ template "lookout-html-analyzer.name" . }}
    chart: {{ template "lookout-html-analyzer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}
      protocol: TCP
  selector:
    app: {{ template "lookout-html-analyzer.name" . }}
    release: {{ .Release.Name }}
